#!/bin/bash
### BEGIN INIT INFO
# Provides:          tallylights.sh
# Required-Start:    network service
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Java applicaiton using a web-socket client
# Description:       OBS Tally lights
### END INIT INFO

do_start()
{

nohup sudo su - pi {INSTDIR}/tallylights.sh > /var/log/tally.log &

}

do_stop()
{

pid=`ps -ef | grep java | grep Aumc | grep -v grep | awk '{print $2}'`
if [ ! ${pid:-X} = "X" ]
then
    kill $pid
fi
}

case "$1" in
  start)
        do_start
        ;;

  stop)
        do_stop
        ;;

  status)
       pid=`ps -ef | grep java | grep Aumc | grep -v grep | awk '{print $2}'`
       if [ ! ${pid:-X} = "X" ]
       then 
           echo "process is running as pid $pid"
       else
           echo "process is not running"
       fi
       ;;

  restart)
       do_stop
       do_start
       ;;

  *)
         echo "Usage: $SCRIPTNAME {start|stop|status|start}" >&2
        exit 3
        ;;
esac


